services:
  - type: worker
    name: discord-music-bot
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python bot.py
    envVars:
      - key: TOKEN
        sync: false
      - key: PREFIX
        value: "!"
